[package]
name = "c_nft_nifs"
version = "0.1.0"
edition = "2021"

[lib]
name = "c_nft_nifs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.29.1"
solana-sdk = "1.16.0"
solana-client = "1.16.0"
mpl-bubblegum = "1.0.0"
mpl-token-metadata = "3.0.1"
bs58 = "0.5"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0.12"
arrayref = "0.3.7"
lazy_static = "1.4"
arc-swap = "1.6"
spl-account-compression = "0.2.0"
spl-token = "4.0"
spl-noop = "0.1.0"
